media:
  input: news-images
  output: /news-images

content:
  - name: news
    label: お知らせ管理
    type: file
    path: news.json
    format: json
    fields:
      - name: items
        label: お知らせ一覧
        type: list
        fields:
          - name: id
            label: ID（自動）
            type: string
            hidden: true
          - name: date
            label: 日付
            type: date
            options:
              format: YYYY-MM-DD
          - name: category
            label: カテゴリ
            type: select
            options:
              values:
                - お知らせ
                - セール
                - 新入荷
                - イベント
                - 休業日
          - name: title
            label: タイトル
            type: string
          - name: image
            label: サムネイル写真
            type: image
            optional: true
          - name: body
            label: 本文
            type: text
