media:
  input: news-images
  output: /news-images

content:
  - name: news
    label: お知らせ管理
    type: file
    path: news.json
    fields:
      - name: items
        label: お知らせ
        type: list
        fields:
          - name: id
            label: ID
            type: string
          - name: date
            label: 日付
            type: date
          - name: category
            label: カテゴリ
            type: select
            options:
              - お知らせ
              - セール
              - 新入荷
              - イベント
              - 休業日
          - name: title
            label: タイトル
            type: string
          - name: image
            label: サムネイル写真
            type: image
            optional: true
          - name: body
            label: 本文
            type: text
